version: "3"
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENERS=yes
    depends_on:
      - zookeeper

  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: kunal
      POSTGRES_PASSWORD: kb@526688
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: kunalborade8805@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 526688
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin